#!/usr/bin/env bash
# gen-staging-env.sh — generates a ready-to-use staging .env and prints it to stdout.
#
# Usage (run once, then set as GitHub secret):
#   STAGING_HOST=1.2.3.4 bash infra/gen-staging-env.sh > /tmp/staging.env
#   gh secret set STAGING_ENV --env staging < /tmp/staging.env
#   rm /tmp/staging.env
#
# STAGING_HOST is the VPS IP/hostname (used for CORS + public URLs).
# If omitted, placeholder values are used — replace them in the .env after generation.
#
# No external tools beyond openssl and coreutils are required.
# All generated secrets are random — re-run to rotate. Existing DB volumes survive
# a secret rotation because DATABASE_URL / REDIS_URL stay consistent within a deploy.

set -euo pipefail

rand_hex() { openssl rand -hex "$1"; }

# Public hostname — used for CORS / public URL vars. Docker compose env_file
# does NOT expand shell variables, so we bake the value in at generation time.
HOST="${STAGING_HOST:-REPLACE_WITH_VPS_IP}"

# ── Postgres ─────────────────────────────────────────────────────────────────
PG_USER="kdl_staging"
PG_PASSWORD="$(rand_hex 16)"
PG_DB="kdl_staging_db"
# Inside the docker compose network the service name is used, not localhost.
DATABASE_URL="postgresql://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DB}"

# ── Redis ─────────────────────────────────────────────────────────────────────
REDIS_PASSWORD="$(rand_hex 16)"
REDIS_URL="redis://:${REDIS_PASSWORD}@redis:6379"

# ── JWT ───────────────────────────────────────────────────────────────────────
JWT_SECRET="$(rand_hex 32)"
JWT_REFRESH_SECRET="$(rand_hex 32)"

# ── MinIO ─────────────────────────────────────────────────────────────────────
MINIO_USER="kdl_staging_minio"
MINIO_PASSWORD="$(rand_hex 16)"

# ── MeiliSearch ───────────────────────────────────────────────────────────────
MEILI_MASTER_KEY="$(rand_hex 24)"
# Scoped keys are normally minted via the MeiliSearch API after first boot.
# Placeholder values below keep the app from crashing; replace after first deploy
# by running: curl -X POST http://<host>:7700/keys -H "Authorization: Bearer $MEILI_MASTER_KEY" ...
MEILI_SCOPED_KEY="replace-after-first-boot-see-meilisearch-docs"

# ── App encryption ────────────────────────────────────────────────────────────
APP_ENCRYPTION_KEY="$(rand_hex 32)"

cat <<ENV
# ── Staging .env — generated by infra/gen-staging-env.sh ──────────────────
# DO NOT commit this file. Set it as a GitHub secret:
#   gh secret set STAGING_ENV --env staging < /tmp/staging.env
#
# AI keys are set to the built-in "local" fallback (KDL-262).
# External API keys (Stripe, Razorpay, SMTP, Sentry) are OPTIONAL —
# the app runs without them; only those specific features are unavailable.

NODE_ENV=staging
APP_PORT=4000
FRONTEND_URL=http://${HOST}
BACKEND_URL=http://${HOST}/api
AI_SERVICES_URL=http://ai-services:5000

# ── Database ──────────────────────────────────────────────────────────────────
POSTGRES_USER=${PG_USER}
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=${PG_DB}
DATABASE_URL=${DATABASE_URL}

# ── Redis ─────────────────────────────────────────────────────────────────────
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=${REDIS_URL}

# ── JWT ───────────────────────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# ── AI (two-brain routing — KDL-262 "local" fallback, no key needed) ─────────
# Set to real keys to use cloud models; "local" uses the built-in fallback.
ANTHROPIC_API_KEY=local
OPENROUTER_API_KEY=local
OPENROUTER_DEFAULT_MODEL=moonshot-ai/moonshot-v1-32k
OPENROUTER_DAILY_BUDGET=2.00

# ── MinIO (object storage) ────────────────────────────────────────────────────
MINIO_ROOT_USER=${MINIO_USER}
MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
MINIO_ENDPOINT=minio
MINIO_PORT=9000
MINIO_USE_SSL=false
MINIO_ACCESS_KEY=${MINIO_USER}
MINIO_SECRET_KEY=${MINIO_PASSWORD}
MINIO_BUCKET=kdl-media
MINIO_PUBLIC_ENDPOINT=${HOST}
MINIO_PUBLIC_PORT=9002
STORAGE_DRIVER=minio

# ── MeiliSearch ───────────────────────────────────────────────────────────────
MEILISEARCH_HOST=http://meilisearch:7700
MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
MEILISEARCH_API_KEY=${MEILI_SCOPED_KEY}
MEILI_SEARCH_API_KEY=${MEILI_SCOPED_KEY}

# ── App-level encryption ──────────────────────────────────────────────────────
APP_ENCRYPTION_KEY=${APP_ENCRYPTION_KEY}

# ── CORS ──────────────────────────────────────────────────────────────────────
CORS_ORIGIN=http://${HOST}

# ── ChromaDB ──────────────────────────────────────────────────────────────────
CHROMADB_URL=http://chromadb:8000

# ── External API keys (OPTIONAL — fallbacks active when unset) ────────────────
# Payments — app runs without these; payment flows return 501
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=

# Email — app falls back to console logging when unset
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=KDL Staging <noreply@staging.kdl.local>

# Error tracking — app runs without this
SENTRY_DSN=

# Voice transcription — Whisper endpoint disabled when unset
OPENAI_API_KEY=
ENV
